import SwiftUI

/// "Insights" card: ranked, plain-language observations about the latest scan
/// (computed locally), plus an optional one-click AI interpretation via a cheap
/// LLM using the user's own key.
struct InsightsCard: View {
    @EnvironmentObject private var storageVM: StorageViewModel

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            header

            VStack(spacing: 8) {
                ForEach(storageVM.insights) { insight in
                    insightRow(insight)
                }
            }

            aiSection
        }
        .padding(20)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(.regularMaterial)
        .clipShape(RoundedRectangle(cornerRadius: 22, style: .continuous))
    }

    private var header: some View {
        HStack {
            Text("Insights")
                .font(.title3.weight(.semibold))
            Spacer()
            Button {
                storageVM.requestAISummary()
            } label: {
                Label(storageVM.isGeneratingAISummary ? "Asking AI…" : "Explain with AI",
                      systemImage: "sparkles")
            }
            .buttonStyle(.bordered)
            .tint(.purple)
            .disabled(storageVM.isGeneratingAISummary || !storageVM.hasActionableInsights)
            .help("Send an aggregated summary (category sizes, folder names) to a cheap AI model for a plain-English readout. Uses your own API key.")
        }
    }

    private func insightRow(_ insight: StorageInsight) -> some View {
        HStack(alignment: .top, spacing: 12) {
            Image(systemName: insight.symbol)
                .foregroundStyle(insight.tint)
                .frame(width: 22)
                .padding(.top, 1)
            VStack(alignment: .leading, spacing: 2) {
                Text(insight.title)
                    .font(.callout.weight(.semibold))
                Text(insight.detail)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
                if let hint = insight.actionHint {
                    Text(hint)
                        .font(.caption2.weight(.medium))
                        .foregroundStyle(insight.tint)
                        .padding(.top, 1)
                }
            }
            Spacer(minLength: 0)
        }
        .padding(12)
        .background(Color.secondary.opacity(0.06))
        .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
    }

    @ViewBuilder
    private var aiSection: some View {
        if let error = storageVM.aiSummaryError {
            Label(error, systemImage: "exclamationmark.triangle")
                .font(.caption)
                .foregroundStyle(.orange)
                .fixedSize(horizontal: false, vertical: true)
        }
        if let summary = storageVM.aiSummary {
            VStack(alignment: .leading, spacing: 8) {
                Label("AI readout", systemImage: "sparkles")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(.purple)
                Text(summary)
                    .font(.callout)
                    .fixedSize(horizontal: false, vertical: true)
                    .textSelection(.enabled)
                Text("Generated by Claude Haiku from an aggregated summary. Verify before deleting anything.")
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }
            .padding(14)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Color.purple.opacity(0.08))
            .overlay(
                RoundedRectangle(cornerRadius: 14, style: .continuous)
                    .strokeBorder(Color.purple.opacity(0.25), lineWidth: 1)
            )
            .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
        }
    }
}

/// One-time key entry + privacy disclosure before the first AI call.
struct AIKeyEntryDialog: View {
    @State private var key: String = ""
    let onCancel: () -> Void
    let onSave: (String) -> Void

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            HStack(spacing: 12) {
                Image(systemName: "sparkles")
                    .font(.title)
                    .foregroundStyle(.purple)
                VStack(alignment: .leading, spacing: 4) {
                    Text("Explain scans with AI")
                        .font(.title2.weight(.semibold))
                    Text("PulseBar can send a short summary of your scan to a cheap AI model (Claude Haiku) for a plain-English readout.")
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
                Spacer()
            }

            VStack(alignment: .leading, spacing: 8) {
                disclosureRow(icon: "lock.shield", text: "Only aggregated data is sent: category sizes, top folder names (abbreviated with ~), and disk totals. Never a full file listing.")
                disclosureRow(icon: "key", text: "Uses your own Anthropic API key, stored in your macOS Keychain — never in plain text or sent anywhere else.")
                disclosureRow(icon: "network", text: "The summary goes to Anthropic's API over HTTPS. Don't enable this if your folder names are sensitive.")
            }
            .padding(14)
            .background(.regularMaterial)
            .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))

            VStack(alignment: .leading, spacing: 6) {
                Text("Anthropic API key")
                    .font(.caption.weight(.medium))
                    .foregroundStyle(.secondary)
                SecureField("sk-ant-…", text: $key)
                    .textFieldStyle(.roundedBorder)
                Text("Get one at console.anthropic.com. Billed to your own account (Haiku is very cheap).")
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }

            HStack {
                Spacer()
                Button("Cancel", role: .cancel, action: onCancel)
                    .keyboardShortcut(.cancelAction)
                Button {
                    onSave(key)
                } label: {
                    Label("Save & Explain", systemImage: "sparkles")
                }
                .keyboardShortcut(.defaultAction)
                .buttonStyle(.borderedProminent)
                .tint(.purple)
                .disabled(key.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
            }
        }
        .padding(24)
        .frame(width: 540)
    }

    private func disclosureRow(icon: String, text: String) -> some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: icon)
                .foregroundStyle(.purple)
                .frame(width: 20)
            Text(text)
                .font(.callout)
                .fixedSize(horizontal: false, vertical: true)
            Spacer(minLength: 0)
        }
    }
}
